export const InterfaceItems = {
    festival: {
        1: 'Halloween',
        2: 'Thanksgiving',
        3: "Xmas",
        4: "Lunar New Year",
        5: "Valentine's Day",
        6: "AprilFool's Day",
        7: "Easter",
        8: "St Patrick's Day",
        9: "USA Independence Day",
        10: "PokeMMO's 10th Anniversary",
    },
    category: {
        0: "Normal",
        1: "Ball",
        2: "Berry",
        3: "Seed",
        4: "Box",
        5: "Particle",
        6: "Cosmetic",
    },
    slot: {
        1: "forehead",
        2: "hat",
        3: "hair",
        4: "eyes",
        5: "face",
        6: "back",
        7: "top",
        8: "gloves",
        9: "shoes",
        10: "legs",
        11: "rod",
        12: "bicycle",
    },
    attribute: {
        1: "Untradeable",
        2: "TriggerAnimation",
        4: "Lighting",
        8: "Colorable",
        16: "ExtraAnimation",
    },
    limitations: {
        1: "Time",
        2: "PvP",
        4: "Event",
        8: "Season",
        16: "UltraRareEvent",
    },
    sceneCosmeticParam: {
        0: "Battle",
        1: "Back",
        2: "Front",
        3: "Side",
        4: "Female",
        5: "Male"
    }
}